
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ToDoListAPI.Data
{

using System;
    using System.Collections.Generic;
    
public partial class List
{

    public Nullable<int> UserID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public int KeyID { get; set; }

}

}
