
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ToDoListAPI.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Task
{

    public int UserID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public System.DateTime DeadLine { get; set; }

    public Nullable<bool> Done { get; set; }

    public Nullable<int> ListID { get; set; }

    public int KeyID { get; set; }

}

}
